# Turns a compiled WGSL file into a constexpr C string header, so
# WebGPUDevice.cpp can #include the shader source directly instead of
# reading it from a filesystem at runtime (no --preload-file needed for
# shaders at all -- CLAUDE.md #9). Invoked via `cmake -P` from
# CMakeLists.txt's compile_slang_shader() custom command, one process per
# shader so it participates correctly in the build-time dependency DAG.
#
# Expects IN_FILE, OUT_FILE, SYMBOL_NAME on the command line (-D...).

file(READ "${IN_FILE}" WGSL_SOURCE)

# Raw string delimiter chosen to never collide with WGSL syntax (which has
# no reason to contain this exact token).
set(DELIM "SLANG_WGSL")

file(WRITE "${OUT_FILE}" "// Generated by engine/shaders/EmbedShader.cmake from ${IN_FILE}. Do not edit directly -- edit the .slang source and rebuild.
#pragma once

inline constexpr char ${SYMBOL_NAME}[] = R\"${DELIM}(
${WGSL_SOURCE})${DELIM}\";
")
